[2024-09-25T10:02:02.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T10:02:02.075+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_2.load.cust_hist scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T10:02:02.098+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_2.load.cust_hist scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T10:02:02.099+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-25T10:02:02.124+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): warehouse.step_2.load.cust_hist> on 2024-09-24 00:00:00+00:00
[2024-09-25T10:02:02.138+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=535) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T10:02:02.141+0000] {standard_task_runner.py:72} INFO - Started process 543 to run task
[2024-09-25T10:02:02.143+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'warehouse.step_2.load.cust_hist', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmpm_a6qezp']
[2024-09-25T10:02:02.148+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask warehouse.step_2.load.cust_hist
[2024-09-25T10:02:02.262+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.warehouse.step_2.load.cust_hist scheduled__2024-09-24T00:00:00+00:00 [running]> on host 639d778bfb8f
[2024-09-25T10:02:02.449+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='warehouse.step_2.load.cust_hist' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-25T10:02:02.452+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T10:02:02.486+0000] {base.py:84} INFO - Retrieving connection 'minio'
[2024-09-25T10:02:02.755+0000] {base.py:84} INFO - Retrieving connection 'warehouse_db'
[2024-09-25T10:02:11.389+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-25T10:02:11.403+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T10:02:11.403+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=warehouse.step_2.load.cust_hist, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240925T100202, end_date=20240925T100211
[2024-09-25T10:02:11.460+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-25T10:02:11.481+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T10:02:11.484+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
