[2024-09-25T07:46:04.320+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:46:04.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:46:04.330+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:46:04.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:46:04.348+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:46:04.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:46:04.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:46:04.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.103 seconds
[2024-09-25T07:46:34.976+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:46:34.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:46:34.984+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:46:34.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:46:34.999+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:46:34.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:46:35.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:46:35.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.097 seconds
[2024-09-25T07:47:05.762+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:47:05.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:47:05.775+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:47:05.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:47:05.794+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:47:05.788+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:47:05.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:47:05.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.136 seconds
[2024-09-25T07:47:36.674+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:47:36.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:47:36.682+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:47:36.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:47:36.694+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:47:36.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:47:36.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:47:36.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.079 seconds
[2024-09-25T07:48:07.301+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:48:07.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:48:07.308+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:48:07.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:48:07.320+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:48:07.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:48:07.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:48:07.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.079 seconds
[2024-09-25T07:48:38.121+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:48:38.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:48:38.128+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:48:38.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:48:38.140+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:48:38.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:48:38.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:48:38.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.071 seconds
[2024-09-25T07:49:08.770+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:49:08.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:49:08.777+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:49:08.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:49:08.788+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:49:08.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:49:08.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:49:08.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.083 seconds
[2024-09-25T07:49:39.840+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:49:39.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:49:39.852+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:49:39.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:49:39.868+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:49:39.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:49:39.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:49:39.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.113 seconds
[2024-09-25T07:50:10.738+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:50:10.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:50:10.745+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:50:10.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:50:10.757+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:50:10.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 5, in <module>
    from etl_pipeline.tasks.staging.dellstore_db import dellstore_db
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 4, in <module>
    from etl_pipeline.tasks.staging.components.extract import Extract
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 5, in <module>
    from helper.minio import CustomMinio
  File "/opt/airflow/dags/helper/minio.py", line 2, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-09-25T07:50:10.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:50:10.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 0.077 seconds
[2024-09-25T07:57:30.245+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:57:30.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:57:30.252+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:57:30.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:57:31.947+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:57:31.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T07:57:31.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:57:31.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.742 seconds
[2024-09-25T07:58:02.299+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:58:02.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:58:02.305+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:58:02.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:58:03.446+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:58:03.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T07:58:03.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:58:03.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.197 seconds
[2024-09-25T07:58:33.931+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:58:33.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:58:33.942+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:58:33.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:58:35.542+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:58:35.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T07:58:35.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:58:35.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.667 seconds
[2024-09-25T07:59:06.074+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:59:06.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:59:06.082+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:59:06.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:59:07.179+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:59:07.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T07:59:07.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:59:07.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.143 seconds
[2024-09-25T07:59:37.518+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:59:37.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T07:59:37.527+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:59:37.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:59:39.108+0000] {logging_mixin.py:190} INFO - [2024-09-25T07:59:39.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T07:59:39.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T07:59:39.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.635 seconds
[2024-09-25T08:00:09.354+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:00:09.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:00:09.364+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:00:09.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:00:10.702+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:00:10.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:00:10.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:00:10.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.403 seconds
[2024-09-25T08:00:41.278+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:00:41.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:00:41.286+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:00:41.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:00:42.526+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:00:42.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:00:42.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:00:42.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.281 seconds
[2024-09-25T08:01:13.418+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:01:13.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:01:13.426+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:01:13.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:01:14.577+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:01:14.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:01:14.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:01:14.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.194 seconds
[2024-09-25T08:01:45.129+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:01:45.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:01:45.139+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:01:45.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:01:46.306+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:01:46.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:01:46.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:01:46.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.218 seconds
[2024-09-25T08:02:17.723+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:02:17.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:02:17.734+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:02:17.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:02:19.638+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:02:19.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:02:19.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:02:19.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.988 seconds
[2024-09-25T08:02:50.374+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:02:50.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:02:50.392+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:02:50.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:02:51.724+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:02:51.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:02:51.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:02:51.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.408 seconds
[2024-09-25T08:03:21.853+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:03:21.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:03:21.872+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:03:21.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:03:22.907+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:03:22.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:03:22.908+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:03:22.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.097 seconds
[2024-09-25T08:03:53.093+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:03:53.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:03:53.100+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:03:53.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:03:54.171+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:03:54.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:03:54.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:03:54.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.113 seconds
[2024-09-25T08:04:24.524+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:04:24.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:04:24.532+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:04:24.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:04:25.668+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:04:25.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:04:25.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:04:25.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.188 seconds
[2024-09-25T08:04:55.982+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:04:55.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:04:56.000+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:04:56.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:04:57.060+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:04:57.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:04:57.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:04:57.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.123 seconds
[2024-09-25T08:05:27.392+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:05:27.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:05:27.402+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:05:27.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:05:28.743+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:05:28.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:05:28.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:05:28.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.393 seconds
[2024-09-25T08:05:58.928+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:05:58.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:05:58.947+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:05:58.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:06:00.324+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:06:00.319+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:06:00.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:06:00.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.444 seconds
[2024-09-25T08:06:30.551+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:06:30.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:06:30.560+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:06:30.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:06:31.971+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:06:31.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:06:31.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:06:31.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.463 seconds
[2024-09-25T08:07:02.063+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:07:02.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:07:02.071+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:07:02.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:07:03.526+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:07:03.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:07:03.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:07:03.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.508 seconds
[2024-09-25T08:07:34.542+0000] {processor.py:186} INFO - Started process (PID=559) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:07:34.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:07:34.551+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:07:34.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:07:36.054+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:07:36.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:07:36.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:07:36.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.565 seconds
[2024-09-25T08:08:07.031+0000] {processor.py:186} INFO - Started process (PID=584) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:08:07.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:08:07.038+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:08:07.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:08:08.223+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:08:08.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:08:08.224+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:08:08.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.231 seconds
[2024-09-25T08:08:38.841+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:08:38.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:08:38.848+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:08:38.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:08:40.027+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:08:40.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:08:40.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:08:40.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.228 seconds
[2024-09-25T08:09:10.895+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:09:10.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:09:10.906+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:09:10.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:09:12.088+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:09:12.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:09:12.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:09:12.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.239 seconds
[2024-09-25T08:09:42.616+0000] {processor.py:186} INFO - Started process (PID=659) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:09:42.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:09:42.624+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:09:42.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:09:43.969+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:09:43.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:09:43.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:09:43.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.396 seconds
[2024-09-25T08:10:14.889+0000] {processor.py:186} INFO - Started process (PID=684) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:10:14.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:10:14.899+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:10:14.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:10:16.302+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:10:16.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:10:16.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:10:16.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.460 seconds
[2024-09-25T08:10:46.975+0000] {processor.py:186} INFO - Started process (PID=716) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:10:46.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:10:46.988+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:10:46.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:10:49.637+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:10:49.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:10:49.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:10:49.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 2.729 seconds
[2024-09-25T08:11:20.178+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:11:20.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:11:20.188+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:11:20.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:11:22.164+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:11:22.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:11:22.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:11:22.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 2.045 seconds
[2024-09-25T08:11:52.655+0000] {processor.py:186} INFO - Started process (PID=766) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:11:52.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:11:52.667+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:11:52.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:11:54.323+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:11:54.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:11:54.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:11:54.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.717 seconds
[2024-09-25T08:12:24.548+0000] {processor.py:186} INFO - Started process (PID=791) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:12:24.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:12:24.559+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:12:24.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:12:25.742+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:12:25.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:12:25.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:12:25.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.244 seconds
[2024-09-25T08:12:55.882+0000] {processor.py:186} INFO - Started process (PID=816) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:12:55.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:12:55.892+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:12:55.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:12:57.230+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:12:57.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:12:57.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:12:57.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.389 seconds
[2024-09-25T08:13:27.476+0000] {processor.py:186} INFO - Started process (PID=841) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:13:27.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:13:27.485+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:13:27.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:13:28.918+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:13:28.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:13:28.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:13:28.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.484 seconds
[2024-09-25T08:13:59.825+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:13:59.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:13:59.835+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:13:59.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:14:01.084+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:14:01.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:14:01.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:14:01.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.303 seconds
[2024-09-25T08:14:32.145+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:14:32.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:14:32.156+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:14:32.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:14:33.569+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:14:33.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:14:33.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:14:33.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.468 seconds
[2024-09-25T08:15:05.073+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:15:05.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:15:05.082+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:15:05.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:15:06.526+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:15:06.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:15:06.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:15:06.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.498 seconds
[2024-09-25T08:15:36.978+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:15:36.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:15:36.997+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:15:36.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:15:38.148+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:15:38.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:15:38.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:15:38.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.207 seconds
[2024-09-25T08:16:08.400+0000] {processor.py:186} INFO - Started process (PID=968) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:16:08.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:16:08.419+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:16:08.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:16:09.592+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:16:09.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:16:09.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:16:09.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.238 seconds
[2024-09-25T08:16:39.721+0000] {processor.py:186} INFO - Started process (PID=993) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:16:39.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:16:39.733+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:16:39.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:16:42.515+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:16:42.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:16:42.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:16:42.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 2.883 seconds
[2024-09-25T08:17:13.236+0000] {processor.py:186} INFO - Started process (PID=1018) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:17:13.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:17:13.258+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:17:13.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:17:15.965+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:17:15.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:17:15.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:17:16.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 2.824 seconds
[2024-09-25T08:17:46.447+0000] {processor.py:186} INFO - Started process (PID=1043) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:17:46.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:17:46.463+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:17:46.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:17:48.382+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:17:48.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:17:48.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:17:48.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.989 seconds
[2024-09-25T08:18:19.202+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:18:19.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:18:19.212+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:18:19.211+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:18:20.784+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:18:20.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:18:20.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:18:20.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.630 seconds
[2024-09-25T08:18:51.026+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:18:51.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:18:51.040+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:18:51.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:18:52.309+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:18:52.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:18:52.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:18:52.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.349 seconds
[2024-09-25T08:19:22.738+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:19:22.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:19:22.746+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:19:22.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:19:23.979+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:19:23.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:19:23.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:19:24.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.294 seconds
[2024-09-25T08:19:54.289+0000] {processor.py:186} INFO - Started process (PID=1148) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:19:54.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:19:54.295+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:19:54.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:19:55.405+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:19:55.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:19:55.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:19:55.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.151 seconds
[2024-09-25T08:20:25.722+0000] {processor.py:186} INFO - Started process (PID=1173) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:20:25.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:20:25.730+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:20:25.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:20:27.103+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:20:27.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:20:27.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:20:27.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.797 seconds
[2024-09-25T08:20:57.717+0000] {processor.py:186} INFO - Started process (PID=1198) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:20:57.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:20:57.724+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:20:57.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:20:59.127+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:20:59.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:20:59.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:20:59.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.456 seconds
[2024-09-25T08:21:29.230+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:21:29.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:21:29.249+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:21:29.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:21:30.780+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:21:30.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:21:30.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:21:30.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.608 seconds
[2024-09-25T08:22:01.610+0000] {processor.py:186} INFO - Started process (PID=1248) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:22:01.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:22:01.630+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:22:01.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:22:03.098+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:22:03.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:22:03.100+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:22:03.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.917 seconds
[2024-09-25T08:22:33.746+0000] {processor.py:186} INFO - Started process (PID=1274) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:22:33.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:22:33.756+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:22:33.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:22:36.094+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:22:36.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:22:36.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:22:36.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 2.399 seconds
[2024-09-25T08:23:06.438+0000] {processor.py:186} INFO - Started process (PID=1300) to work on /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:23:06.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline/run.py for tasks to queue
[2024-09-25T08:23:06.444+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:23:06.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:23:07.667+0000] {logging_mixin.py:190} INFO - [2024-09-25T08:23:07.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline/run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline/run.py", line 29, in <module>
    etl_pipeline()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_pipeline/run.py", line 25, in etl_pipeline
    staging = dellstore_db(incremental = True) >> dellstore_api() >> dellstore_spreadsheet()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 48, in dellstore_db
    extract() >> load()
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 93, in __call__
    return self._create_task_group(TaskGroup, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/task_group.py", line 101, in _create_task_group
    retval = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/dellstore_db.py", line 11, in extract
    table_to_extract = eval(Variable.get('list_dellstore_table'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable list_dellstore_table does not exist'
[2024-09-25T08:23:07.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline/run.py
[2024-09-25T08:23:07.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline/run.py took 1.267 seconds
